### PR TITLE
[i18n]Update harbour-tint-fr.ts

### PR DESCRIPTION
**Pull request by Quenty31**

### CODE REVIEW

**Comment by attah** [comment]
Thanks! In the meantime i went looking and got another suggestion: "Dépareillage en cours", i guess yours is more the same look and feel as other remorse timers (which is the intended use)?

**Comment by Quenty31** [comment]
This was my first choice but it's not in the dictionary :( 
I wouldn't like to provide a word that is not correct you know =/
That's why I put «end of association with the bridge»

**Comment by attah** [comment]
As a Swede that sounds very strange, we make up words all the time, but he did give the same disclaimer "only of this is a real word", so yours it is then.

**Comment by Quenty31** [comment]
Yes French is more verbose ^^

**Pull request merged**
