### PR TITLE
Finnish translation

### PR DESCRIPTION
**Pull request by juhi24**
I was not sure if the context of the untranslated string "Pairing" was as in 'currently pairing' or 'the pairing process'.

The content of this pull request is available under the MIT license. The license text can be found in https://opensource.org/licenses/MIT

### CODE REVIEW

**Comment by attah** [comment]
Hmm, i think i mean to say "Currently Pairing" or "Pairing in Progress". It is the title of the pairing page.
If you wish to licence your contribution (as opposed to giving it away non-exclusively, no strings attached), please do include proper terms, headers and attribution that you will be happy with (limited to "your" component). MIT is a fair choice though.

**Comment by juhi24** [comment]
There's no such thing as giving it away. "No strings attached" is a license. The point is that there is always a license when code or software is handed over. You are very right that the terms should be clear and visible. The same applies to this awesome piece of software you have written.

I would really appreciate if you'd include the license terms in a file in the root of the project, so that contributors would know the terms under which their contributions are distributed without having to include their own terms in each contribution. One reason I'm asking this is because I'm planning to continue contributing. At the current situation it's questionable if it's legal for me to make these PRs.

**Comment by attah** [comment]
> There's no such thing as giving it away. "No strings attached" is a license.

That's splitting hairs. I will assume contributions are gifts unless otherwise noted (as you did).
It would indeed suck to have a project that you contributed heavily to close up on you.
So far contributions have been isolated and/or minor enough for it not to really matter.
I'll sleep on the licence choice.

**Comment by attah** [comment]
How about now?

**Comment by juhi24** [comment]
Excellent choice! Thank you.

I finished the last bit of Finnish translation in this PR. Should be ready for merging.

**Comment by attah** [comment]
I'll let the changes stew for a little while so i can get some actual use in before making it available in store.
Hopefully i can get some answers in the next few days to questions i posted on the Hue developer forums too.

**Comment by juhi24** [comment]
I don't mind a little delay. There are propably bunch of little things we can do before a release.

**Pull request merged**
