### PR TITLE
Colored hue slider

### PR DESCRIPTION
**Pull request by juhi24**
Added visual color clue to the hue slider so that the user does not need to select color blindly.

Changes introduced in this PR are purely cosmetic. The underlying functionality remains the same. It is a lot of code since I couldn't inherit Slider. The ColorSlider code is adapted from `/usr/lib/qt5/qml/com/jolla/gallery/ambience/ColorSlider.qml` with modifications.

### CODE REVIEW

**Comment by attah** [comment]
Looks, and works, great. Looks quite complex though, and i guess the source explains why. Probably built with all the dark arts covered :) Which brings me to that i'm not entirely sold on introducing potential copyright issues. The functionality as such though is great, id would be neat for color temperature too.
I had previously considered doing a big X/Y-mode area for color picking, but since i'm not much of a fan of colors beyond shades of white that didn't get any attention. Honestly not sure how to proceed.

**Comment by juhi24** [comment]
Copyright is an important point! I would guess it's open source. Things to figure out:

* Under what license is the original ColorSlider.qml?
* Under what license is harbour-tint?
* Are those two licenses compatible?

**Comment by attah** [comment]
Well, I assume that it is part of the proprietary Jolla applications, and not open source (despite being readable).
I have yet to figure out a good license for harbour-tint, but am making it freely available in good faith, contributing to the community. As such i guess i by default retain all rights to it. However nobody will get any quarrel from me for reusing some components/concepts or resurrecting it if ever abandoned (well, unless they are being abusive in doing so). If this pull ends up making me need to choose some proper open source licence, that's fine.

**Comment by juhi24** [comment]
Damn, seems you were right about the Jolla licensing:
```bash
$ rpm -qf /usr/lib/qt5/qml/com/jolla/gallery/ambience/ColorSlider.qml
jolla-gallery-ambience-0.2.23-1.11.1.jolla.armv7hl
$ devel-su pkcon get-details jolla-gallery-ambience 
Password: 
Resolving                                                                                                                                                                                                                                                                                                                    
Getting details                                                                                                                                                                                                                                                                                                               
Querying                                                                                                                                                                                                                                                                                                                     
Finished                                                                                                                                                                                                                                                                                                                     
Package description
  package:     jolla-gallery-ambience-0.2.23-1.11.1.jolla.armv7hl
  summary:     Jolla Gallery Ambience extension plugin
  license:     Proprietary
```

So basically, a complete rewrite would be needed. Some GPL code exists, that might save us from writing all from scrach: https://github.com/sailfishos/sailfish-qtcreator/blob/master/share/qtcreator/qmldesigner/propertyEditorQmlSources/imports/HelperWidgets/HueSlider.qml

Being clear about the license for Tint would be much appreciated. Otherwise it's questionable if I or anyone else is even allowed to fork and modify your code. Personally I nowadays use the super permissive MIT in my projects, but be it GPL, Apache or all rights reserved, anything is better than not being clear about it. For the sake of encouraging more PRs ;) https://choosealicense.com/

**Comment by juhi24** [comment]
Finnish translation was supposed to be a separate PR. I don't know how it ended up here.

**Comment by juhi24** [comment]
> Finnish translation was supposed to be a separate PR. I don't know how it ended up here.

I guess I should have made a separate branch for that one.

**Comment by attah** [comment]
Hmm, bringing in GPL3 is a pretty big step compared to MIT, MPL, BSD etc. But i'm not sure i have reason to care as a owner/maintainer... One idea is to ask Jolla nicely about how they feel about reusing this relatively small snippet of code.

**Comment by juhi24** [comment]
I was already writing them ;)

AFAIK, using a GPL component in the project would be a no-brainer; You'd simply need an extra copying notice regarding that bit. Rest of the code can be licensed under whatever. I think you would be complying nicely with GPL since you'd have the modified code in the open.

**Comment by attah** [comment]
I'm not so sure about that, since the whole point of GPL is that it is contagious... Feel free to prove me wrong :)

**Comment by juhi24** [comment]
Forking a GPL project is where it's contagious. Being able to use GPL licensed components in your project, whatever it's license, is the whole point of GPL. 

As far as you publish any modifications, under GPL, that you made _in the GPL components that you used_. Or how do we suppose, e.g., SFOS is using tons of GPL stuff under the hood? :)

**Comment by attah** [comment]
> Or how do we suppose, e.g., SFOS is using tons of GPL stuff under the hood? :)
Separate processes, dynamic linking.

**Comment by juhi24** [comment]
Hmm. According to wikipedia you are correct again: https://en.wikipedia.org/wiki/License_compatibility#GPL_compatibility

**Comment by attah** [comment]
I have managed to get the same result with inheriting from Slider, by replacing the _backgroundItem, hiding the _progressBarItem and moving _highlightItem to z=1. Not particularly neat, but it seems to work. Now lets find out how to re-implement the color gradient... I'll trow up whatever i have when i'm either done or otherwise stop working on it for the time being. Feel free to poke me on IRC if you like.

**Comment by attah** [comment]
Let me amend that; i don't need to replace anything, i can just place it referencing the original _backgrounditem.

**Comment by attah** [comment]
What do you think about this? https://github.com/attah/harbour-tint/commit/1ffc36be242075be820ea8488be38ff87d4a58e7

**Comment by juhi24** [comment]
Works and looks almost exactly like the original PR. Your implementation is much neater in my opinion. Well done!

Now it should be simple enough to apply the same for color temperature.

It would be super neat if the saturation slider would dynamically update to match the current color selection.

Anyway these ideas are not directly related to this PR. It can be closed now. Thanks! I will make a separate one for the translation.

**Comment by attah** [comment]
Yeah, i tried it for color temperature, but am not happy with the crude conversion i made to shades of yellow and white. It doesn't actually go in to blue... so it looks a bit off compared to what a user might expect. I'll tinker with it some more when i feel inspired.

>It would be super neat if the saturation slider would dynamically update to match the current color selection.
I'll look in to that... not sure how to dig that our from my gradient.

**Comment by attah** [comment]
One reasonable pre-requisite for changing the color of the saturation slider is to sync the hue with the color temperature, if it is used last.
I have tried reading back the resulting hue after setting color temperature. It is waaaay too slow and unreliable. Almost worth a ticket to support. The obvious workaround is local mapping, but currently i have no way of calculating that as it uses both yellow and blue with vastly different saturations.

**Pull request closed without merging**
